export const ADD_DOCTOR="ADD_DOCTOR";
export const UPDATE_DOCTOR="UPDATE_DOCTOR";
export const LOADING_DOCTOR="LOADING_DOCTOR";
export const DELETE_DOCTOR="DELETE_DOCTOR";
export const ERROR_DOCTOR="ERROR_DOCTOR";
export const ADD_APPOINTMENTS="ADD_APPOINTMENTS";